spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recipe_dev?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: recipe_dev_user
    password: toni
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: guru_database_create.sql